# Generated by Django 2.0.13 on 2019-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0002_review2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title3', models.CharField(max_length=200)),
                ('radio3', models.CharField(max_length=200)),
                ('writer3', models.CharField(max_length=100)),
                ('description3', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
